# Generated by Django 4.0.5 on 2022-07-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last_name')),
            ],
            options={
                'verbose_name': 'man',
                'verbose_name_plural': 'people',
                'ordering': ['first_name', 'last_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFirstApp.person', verbose_name='xozain')),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pets',
                'ordering': ['owner'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.DeleteModel(
            name='Myfirst',
        ),
    ]
